// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: consistent_hash.proto

package consistent_hash

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapkeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *MapkeyRequest) Reset() {
	*x = MapkeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consistent_hash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapkeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapkeyRequest) ProtoMessage() {}

func (x *MapkeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consistent_hash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapkeyRequest.ProtoReflect.Descriptor instead.
func (*MapkeyRequest) Descriptor() ([]byte, []int) {
	return file_consistent_hash_proto_rawDescGZIP(), []int{0}
}

func (x *MapkeyRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type MapkeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MapkeyResponse) Reset() {
	*x = MapkeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consistent_hash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapkeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapkeyResponse) ProtoMessage() {}

func (x *MapkeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consistent_hash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapkeyResponse.ProtoReflect.Descriptor instead.
func (*MapkeyResponse) Descriptor() ([]byte, []int) {
	return file_consistent_hash_proto_rawDescGZIP(), []int{1}
}

func (x *MapkeyResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type AddkeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AddkeyRequest) Reset() {
	*x = AddkeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consistent_hash_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddkeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddkeyRequest) ProtoMessage() {}

func (x *AddkeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consistent_hash_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddkeyRequest.ProtoReflect.Descriptor instead.
func (*AddkeyRequest) Descriptor() ([]byte, []int) {
	return file_consistent_hash_proto_rawDescGZIP(), []int{2}
}

func (x *AddkeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AddkeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddkeyResponse) Reset() {
	*x = AddkeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consistent_hash_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddkeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddkeyResponse) ProtoMessage() {}

func (x *AddkeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consistent_hash_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddkeyResponse.ProtoReflect.Descriptor instead.
func (*AddkeyResponse) Descriptor() ([]byte, []int) {
	return file_consistent_hash_proto_rawDescGZIP(), []int{3}
}

func (x *AddkeyResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RemoveServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *RemoveServerRequest) Reset() {
	*x = RemoveServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consistent_hash_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerRequest) ProtoMessage() {}

func (x *RemoveServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consistent_hash_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerRequest.ProtoReflect.Descriptor instead.
func (*RemoveServerRequest) Descriptor() ([]byte, []int) {
	return file_consistent_hash_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveServerRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type RemoveServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result map[string]string `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RemoveServerResponse) Reset() {
	*x = RemoveServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consistent_hash_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerResponse) ProtoMessage() {}

func (x *RemoveServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consistent_hash_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerResponse.ProtoReflect.Descriptor instead.
func (*RemoveServerResponse) Descriptor() ([]byte, []int) {
	return file_consistent_hash_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveServerResponse) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_consistent_hash_proto protoreflect.FileDescriptor

var file_consistent_hash_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x22, 0x27, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x6b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x22, 0x28, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x21, 0x0a, 0x0d, 0x41,
	0x64, 0x64, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x28,
	0x0a, 0x0e, 0x41, 0x64, 0x64, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x9c, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x31, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x39, 0x0a, 0x0b, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x8f, 0x02, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x51, 0x0a, 0x0c, 0x4b, 0x65, 0x79,
	0x4d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x73,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x70, 0x6b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x73,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x4d, 0x61, 0x70, 0x6b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x06,
	0x41, 0x64, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x41, 0x64, 0x64, 0x6b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x41, 0x64, 0x64, 0x6b, 0x65, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0c, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x63, 0x6f, 0x6e, 0x73,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x63, 0x6f,
	0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consistent_hash_proto_rawDescOnce sync.Once
	file_consistent_hash_proto_rawDescData = file_consistent_hash_proto_rawDesc
)

func file_consistent_hash_proto_rawDescGZIP() []byte {
	file_consistent_hash_proto_rawDescOnce.Do(func() {
		file_consistent_hash_proto_rawDescData = protoimpl.X.CompressGZIP(file_consistent_hash_proto_rawDescData)
	})
	return file_consistent_hash_proto_rawDescData
}

var file_consistent_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_consistent_hash_proto_goTypes = []any{
	(*MapkeyRequest)(nil),        // 0: consistent_hash.MapkeyRequest
	(*MapkeyResponse)(nil),       // 1: consistent_hash.MapkeyResponse
	(*AddkeyRequest)(nil),        // 2: consistent_hash.AddkeyRequest
	(*AddkeyResponse)(nil),       // 3: consistent_hash.AddkeyResponse
	(*RemoveServerRequest)(nil),  // 4: consistent_hash.RemoveServerRequest
	(*RemoveServerResponse)(nil), // 5: consistent_hash.RemoveServerResponse
	nil,                          // 6: consistent_hash.RemoveServerResponse.ResultEntry
}
var file_consistent_hash_proto_depIdxs = []int32{
	6, // 0: consistent_hash.RemoveServerResponse.result:type_name -> consistent_hash.RemoveServerResponse.ResultEntry
	0, // 1: consistent_hash.ConsistentHash.KeyMapServer:input_type -> consistent_hash.MapkeyRequest
	2, // 2: consistent_hash.ConsistentHash.AddKey:input_type -> consistent_hash.AddkeyRequest
	4, // 3: consistent_hash.ConsistentHash.RemoveServer:input_type -> consistent_hash.RemoveServerRequest
	1, // 4: consistent_hash.ConsistentHash.KeyMapServer:output_type -> consistent_hash.MapkeyResponse
	3, // 5: consistent_hash.ConsistentHash.AddKey:output_type -> consistent_hash.AddkeyResponse
	5, // 6: consistent_hash.ConsistentHash.RemoveServer:output_type -> consistent_hash.RemoveServerResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_consistent_hash_proto_init() }
func file_consistent_hash_proto_init() {
	if File_consistent_hash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_consistent_hash_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MapkeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consistent_hash_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MapkeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consistent_hash_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddkeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consistent_hash_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AddkeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consistent_hash_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consistent_hash_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consistent_hash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consistent_hash_proto_goTypes,
		DependencyIndexes: file_consistent_hash_proto_depIdxs,
		MessageInfos:      file_consistent_hash_proto_msgTypes,
	}.Build()
	File_consistent_hash_proto = out.File
	file_consistent_hash_proto_rawDesc = nil
	file_consistent_hash_proto_goTypes = nil
	file_consistent_hash_proto_depIdxs = nil
}
