// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.11.0
//  VPP:              25.06-rc0~112-ge1705791e
// source: plugins/hdrcap.api.json

// Package hdrcap contains generated bindings for API file hdrcap.api.
//
// Contents:
// -  2 messages
package hdrcap

import (
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
	interface_types "mygit.com/consistent_hashing/vpp_demo/vppbinapi/interface_types"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "hdrcap"
	APIVersion = "0.1.0"
	VersionCrc = 0x3a1a2c50
)

// /* Version and type recitations
// HdrcapEnableDisable defines message 'hdrcap_enable_disable'.
type HdrcapEnableDisable struct {
	EnableDisable bool                           `binapi:"bool,name=enable_disable" json:"enable_disable,omitempty"`
	SwIfIndex     interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *HdrcapEnableDisable) Reset()               { *m = HdrcapEnableDisable{} }
func (*HdrcapEnableDisable) GetMessageName() string { return "hdrcap_enable_disable" }
func (*HdrcapEnableDisable) GetCrcString() string   { return "3865946c" }
func (*HdrcapEnableDisable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *HdrcapEnableDisable) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1 // m.EnableDisable
	size += 4 // m.SwIfIndex
	return size
}
func (m *HdrcapEnableDisable) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.EnableDisable)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	return buf.Bytes(), nil
}
func (m *HdrcapEnableDisable) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.EnableDisable = buf.DecodeBool()
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	return nil
}

// HdrcapEnableDisableReply defines message 'hdrcap_enable_disable_reply'.
type HdrcapEnableDisableReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *HdrcapEnableDisableReply) Reset()               { *m = HdrcapEnableDisableReply{} }
func (*HdrcapEnableDisableReply) GetMessageName() string { return "hdrcap_enable_disable_reply" }
func (*HdrcapEnableDisableReply) GetCrcString() string   { return "e8d4e804" }
func (*HdrcapEnableDisableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *HdrcapEnableDisableReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *HdrcapEnableDisableReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *HdrcapEnableDisableReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

func init() { file_hdrcap_binapi_init() }
func file_hdrcap_binapi_init() {
	api.RegisterMessage((*HdrcapEnableDisable)(nil), "hdrcap_enable_disable_3865946c")
	api.RegisterMessage((*HdrcapEnableDisableReply)(nil), "hdrcap_enable_disable_reply_e8d4e804")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*HdrcapEnableDisable)(nil),
		(*HdrcapEnableDisableReply)(nil),
	}
}
