// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package hdrcap

import (
	"context"

	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service hdrcap.
type RPCService interface {
	HdrcapEnableDisable(ctx context.Context, in *HdrcapEnableDisable) (*HdrcapEnableDisableReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) HdrcapEnableDisable(ctx context.Context, in *HdrcapEnableDisable) (*HdrcapEnableDisableReply, error) {
	out := new(HdrcapEnableDisableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
