// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package udp_echo_msg

import (
	"context"

	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service udp_echo_msg.
type RPCService interface {
	UDPEchoMsgEnableDisable(ctx context.Context, in *UDPEchoMsgEnableDisable) (*UDPEchoMsgEnableDisableReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) UDPEchoMsgEnableDisable(ctx context.Context, in *UDPEchoMsgEnableDisable) (*UDPEchoMsgEnableDisableReply, error) {
	out := new(UDPEchoMsgEnableDisableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
