unix {
  nodaemon
  log /var/log/vpp/vpp.log
  full-coredump
  interactive 
  cli-listen /run/vpp/cli.sock 
  gid 0
  startup-config /root/consistent_hashing/vpp_demo/config_files/init.vpp
}

api-trace {
  on
}

plugins {
  plugin ip_session_redirect_plugin.so { enable }
}


dpdk {
  dev 0000:13:00.0 {
	name eth0
  }
}